#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Α Β Γ Δ Π Σ Υ Φ Ψ Ω

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart
sxhkd &
picom &
nitrogen &
dunst &
polybar &
feh --bg-center /path/to/your/wallpaper
